name: Build Drivers

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build drivers
      run: |
        sudo apt-get update -y -jj
        sudo apt-get install -y -jj gcc make nasm
        make
        ls -l drivers/*.drv
        zip -9 -j sci-drivers.zip drivers/*.drv
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sci-drivers.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
