name: SCI Driver

on:
  push:
    branches:
      - master
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc make nasm
        make
        ls -l drivers/*.drv
        zip sci-drivers.zip drivers/*.drv
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: sci-drivers.zip
