name: SCI Driver

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
      apt-get update -y && apt-get install -y gcc make nasm
      make
