name: SCI Driver

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc make nasm
        make
        ls -l wip.drv
